#!/bin/bash
echo "==================================="
echo "Email Deliverability Quick Test"
echo "==================================="
echo ""
echo "Step 1: Test your email with Mail-Tester"
echo "   1. Visit: https://www.mail-tester.com"
echo "   2. Copy the test email address shown"
echo "   3. Run this command:"
echo ""
echo "      php artisan tinker"
echo ""
echo "   4. Then paste this (replace the email):"
echo ""
echo "      use App\Services\EmailService;"
echo "      \$emailService = app(EmailService::class);"
echo "      \$emailService->sendVendorInvitation('test-xxxxx@mail-tester.com', 'Test Company');"
echo "      exit"
echo ""
echo "   5. Go back to mail-tester.com and click 'Then check your score'"
echo "   6. Aim for 9/10 or 10/10"
echo ""
echo "==================================="
echo "Most Common Issues:"
echo "==================================="
echo ""
echo "❌ SPF Record Missing"
echo "   → Add TXT record: @ → v=spf1 include:amazonses.com ~all"
echo ""
echo "❌ DKIM Record Missing" 
echo "   → Add TXT record from Resend dashboard"
echo ""
echo "❌ Wrong From Address"
echo "   → Use: noreply@yourdomain.com (not @gmail.com)"
echo ""
echo "❌ Domain Not Verified"
echo "   → Check: https://resend.com/domains"
echo ""
echo "==================================="
