<?php

namespace App\Notifications;

use App\Models\Logistics\Document;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class FleetDocumentExpiryNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        private Document $document,
        private int $daysRemaining,
        private string $alertColour,
        private ?string $extraLine = null
    ) {
        $this->onQueue('notifications');
    }

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $vehicle = $this->document->documentable;
        $tier = "Alert tier: {$this->alertColour}";

        return (new MailMessage)
            ->subject("Fleet document ({$this->alertColour}): {$this->document->document_type} — {$vehicle->plate_number}")
            ->greeting('Fleet document compliance')
            ->line("Vehicle plate: {$vehicle->plate_number}")
            ->line("Document type: {$this->document->document_type}")
            ->line('Expiry date: ' . ($this->document->expires_at?->format('Y-m-d') ?? 'N/A'))
            ->line("Days remaining: {$this->daysRemaining}")
            ->line($tier)
            ->when($this->extraLine, fn (MailMessage $mail) => $mail->line($this->extraLine))
            ->action('View vehicle', url("/logistics/fleet/vehicles/{$vehicle->id}"))
            ->line('This message was generated by the fleet document expiry checker.');
    }

    public function toArray(object $notifiable): array
    {
        $vehicle = $this->document->documentable;

        return [
            'vehicle_id' => $vehicle->id,
            'vehicle_plate' => $vehicle->plate_number,
            'document_type' => $this->document->document_type,
            'expiry_date' => $this->document->expires_at?->format('Y-m-d'),
            'days_remaining' => $this->daysRemaining,
            'alert_colour' => $this->alertColour,
            'recipient_user_id' => $notifiable->getAuthIdentifier(),
            'document_id' => $this->document->id,
            'notification_type' => 'fleet_document_expiry',
            'message' => $this->extraLine,
        ];
    }
}
